### PR TITLE
Added handling for custom databases

### PR DESCRIPTION
**Pull request by nschcolnicov**
This PR is to address this issue:
https://github.com/miRTop/mirtop/issues/90

The database provided via argument is now being taken into account, and I updated the code so that it tries to parse any custom database using either mirbase or mirgenedb parsing, if neither work, it will now display an error message saying that there is no available parser for the custom database

@lpantano

### CODE REVIEW

**Comment by lpantano** [comment]
Thank you, can you bump the version of mirtop and add it to the change log so Conda update the version?

**Comment by lpantano** [comment]
Thank you, some tests are failing. I think it is about the new argument need to be added to all the test, I can play with this next Friday if you don't have the time. Thanks!

**Comment by nschcolnicov** [comment]
Hi @lpantano I updated the files and ran the tests locally, should be working now.

**Comment by lpantano** [comment]
Thank you!

**Pull request merged**
